//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1053 with alias "BasicInfoComponent"
	/// <summary>Базовая Информация</summary>
	public partial interface IBasicInfoComponent : IPublishedContent
	{
		/// <summary>Имя в навигации</summary>
		string NavTitle { get; }

		/// <summary>Заголовок страницы</summary>
		string Title { get; }
	}

	/// <summary>Базовая Информация</summary>
	[PublishedContentModel("BasicInfoComponent")]
	public partial class BasicInfoComponent : PublishedContentModel, IBasicInfoComponent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "BasicInfoComponent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BasicInfoComponent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BasicInfoComponent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Имя в навигации: Название ссылки на страницу в навигационных элементах
		///</summary>
		[ImplementPropertyType("navTitle")]
		public string NavTitle
		{
			get { return GetNavTitle(this); }
		}

		/// <summary>Static getter for Имя в навигации</summary>
		public static string GetNavTitle(IBasicInfoComponent that) { return that.GetPropertyValue<string>("navTitle"); }

		///<summary>
		/// Заголовок страницы: Переопределяет заголовок страницы в браузере (желательно не более 70 символов)
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Заголовок страницы</summary>
		public static string GetTitle(IBasicInfoComponent that) { return that.GetPropertyValue<string>("title"); }
	}
}
