//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Ошибка</summary>
	[PublishedContentModel("ErrorPage")]
	public partial class ErrorPage : PublishedContentModel, IBasicInfoComponent, INavigationComponent, ISeoComponent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ErrorPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ErrorPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ErrorPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Имя в навигации: Название ссылки на страницу в навигационных элементах
		///</summary>
		[ImplementPropertyType("navTitle")]
		public string NavTitle
		{
			get { return Umbraco.Web.PublishedContentModels.BasicInfoComponent.GetNavTitle(this); }
		}

		///<summary>
		/// Заголовок страницы: Переопределяет заголовок страницы в браузере (желательно не более 70 символов)
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.BasicInfoComponent.GetTitle(this); }
		}

		///<summary>
		/// Скрыть из навигации
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.NavigationComponent.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Перенаправление
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public string UmbracoRedirect
		{
			get { return Umbraco.Web.PublishedContentModels.NavigationComponent.GetUmbracoRedirect(this); }
		}

		///<summary>
		/// Альтернативный Url
		///</summary>
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName
		{
			get { return Umbraco.Web.PublishedContentModels.NavigationComponent.GetUmbracoUrlName(this); }
		}

		///<summary>
		/// Meta - Description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SeoComponent.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta - Keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.SeoComponent.GetMetaKeywords(this); }
		}

		///<summary>
		/// Изображение для соц. сетей: Изображение которое будет предложено для парсера соц. сетей и месенджеров.
		///</summary>
		[ImplementPropertyType("shareUrlImage")]
		public IPublishedContent ShareUrlImage
		{
			get { return Umbraco.Web.PublishedContentModels.SeoComponent.GetShareUrlImage(this); }
		}
	}
}
