//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1067 with alias "GlobalDataComponent"
	/// <summary>Глобальные данные</summary>
	public partial interface IGlobalDataComponent : IPublishedContent
	{
		/// <summary>Email для оповещения</summary>
		string Emails { get; }

		/// <summary>Email для связи</summary>
		string GlobalEmail { get; }

		/// <summary>Телефон для связи</summary>
		string GlobalPhone { get; }

		/// <summary>Главное меню</summary>
		IEnumerable<IPublishedContent> MainMenu { get; }

		/// <summary>Соц. сети</summary>
		IEnumerable<IPublishedContent> SocialNetworks { get; }
	}

	/// <summary>Глобальные данные</summary>
	[PublishedContentModel("GlobalDataComponent")]
	public partial class GlobalDataComponent : PublishedContentModel, IGlobalDataComponent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "GlobalDataComponent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GlobalDataComponent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GlobalDataComponent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Email для оповещения
		///</summary>
		[ImplementPropertyType("emails")]
		public string Emails
		{
			get { return GetEmails(this); }
		}

		/// <summary>Static getter for Email для оповещения</summary>
		public static string GetEmails(IGlobalDataComponent that) { return that.GetPropertyValue<string>("emails"); }

		///<summary>
		/// Email для связи
		///</summary>
		[ImplementPropertyType("globalEmail")]
		public string GlobalEmail
		{
			get { return GetGlobalEmail(this); }
		}

		/// <summary>Static getter for Email для связи</summary>
		public static string GetGlobalEmail(IGlobalDataComponent that) { return that.GetPropertyValue<string>("globalEmail"); }

		///<summary>
		/// Телефон для связи
		///</summary>
		[ImplementPropertyType("globalPhone")]
		public string GlobalPhone
		{
			get { return GetGlobalPhone(this); }
		}

		/// <summary>Static getter for Телефон для связи</summary>
		public static string GetGlobalPhone(IGlobalDataComponent that) { return that.GetPropertyValue<string>("globalPhone"); }

		///<summary>
		/// Главное меню
		///</summary>
		[ImplementPropertyType("mainMenu")]
		public IEnumerable<IPublishedContent> MainMenu
		{
			get { return GetMainMenu(this); }
		}

		/// <summary>Static getter for Главное меню</summary>
		public static IEnumerable<IPublishedContent> GetMainMenu(IGlobalDataComponent that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("mainMenu"); }

		///<summary>
		/// Соц. сети
		///</summary>
		[ImplementPropertyType("socialNetworks")]
		public IEnumerable<IPublishedContent> SocialNetworks
		{
			get { return GetSocialNetworks(this); }
		}

		/// <summary>Static getter for Соц. сети</summary>
		public static IEnumerable<IPublishedContent> GetSocialNetworks(IGlobalDataComponent that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("socialNetworks"); }
	}
}
