//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1054 with alias "NavigationComponent"
	/// <summary>Навигационный Компонент</summary>
	public partial interface INavigationComponent : IPublishedContent
	{
		/// <summary>Скрыть из навигации</summary>
		bool UmbracoNaviHide { get; }

		/// <summary>Перенаправление</summary>
		string UmbracoRedirect { get; }

		/// <summary>Альтернативный Url</summary>
		string UmbracoUrlName { get; }
	}

	/// <summary>Навигационный Компонент</summary>
	[PublishedContentModel("NavigationComponent")]
	public partial class NavigationComponent : PublishedContentModel, INavigationComponent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "NavigationComponent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NavigationComponent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NavigationComponent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Скрыть из навигации
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return GetUmbracoNaviHide(this); }
		}

		/// <summary>Static getter for Скрыть из навигации</summary>
		public static bool GetUmbracoNaviHide(INavigationComponent that) { return that.GetPropertyValue<bool>("umbracoNaviHide"); }

		///<summary>
		/// Перенаправление
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public string UmbracoRedirect
		{
			get { return GetUmbracoRedirect(this); }
		}

		/// <summary>Static getter for Перенаправление</summary>
		public static string GetUmbracoRedirect(INavigationComponent that) { return that.GetPropertyValue<string>("umbracoRedirect"); }

		///<summary>
		/// Альтернативный Url
		///</summary>
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName
		{
			get { return GetUmbracoUrlName(this); }
		}

		/// <summary>Static getter for Альтернативный Url</summary>
		public static string GetUmbracoUrlName(INavigationComponent that) { return that.GetPropertyValue<string>("umbracoUrlName"); }
	}
}
