//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1055 with alias "SeoComponent"
	/// <summary>SEO Компонент</summary>
	public partial interface ISeoComponent : IPublishedContent
	{
		/// <summary>Meta - Description</summary>
		string MetaDescription { get; }

		/// <summary>Meta - Keywords</summary>
		string MetaKeywords { get; }

		/// <summary>Изображение для соц. сетей</summary>
		IPublishedContent ShareUrlImage { get; }
	}

	/// <summary>SEO Компонент</summary>
	[PublishedContentModel("SeoComponent")]
	public partial class SeoComponent : PublishedContentModel, ISeoComponent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "SeoComponent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SeoComponent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SeoComponent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meta - Description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return GetMetaDescription(this); }
		}

		/// <summary>Static getter for Meta - Description</summary>
		public static string GetMetaDescription(ISeoComponent that) { return that.GetPropertyValue<string>("metaDescription"); }

		///<summary>
		/// Meta - Keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return GetMetaKeywords(this); }
		}

		/// <summary>Static getter for Meta - Keywords</summary>
		public static string GetMetaKeywords(ISeoComponent that) { return that.GetPropertyValue<string>("metaKeywords"); }

		///<summary>
		/// Изображение для соц. сетей: Изображение которое будет предложено для парсера соц. сетей и месенджеров.
		///</summary>
		[ImplementPropertyType("shareUrlImage")]
		public IPublishedContent ShareUrlImage
		{
			get { return GetShareUrlImage(this); }
		}

		/// <summary>Static getter for Изображение для соц. сетей</summary>
		public static IPublishedContent GetShareUrlImage(ISeoComponent that) { return that.GetPropertyValue<IPublishedContent>("shareUrlImage"); }
	}
}
